#!/bin/bash

# CallFlow AI - One-Click Deploy to Render
# This script creates render.yaml and guides deployment to Render

set -e  # Exit on error

echo "🚀 CallFlow AI - Render Deployment Script"
echo "=========================================="
echo ""

# Create render.yaml
echo "📝 Creating render.yaml configuration..."

cat > render.yaml <<'EOF'
services:
  # Backend Service (FastAPI)
  - type: web
    name: callflowai-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: MONGO_URI
        sync: false  # Set in Render dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 10080
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: N8N_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://callflowai-frontend.onrender.com

  # Frontend Service (Next.js)
  - type: web
    name: callflowai-frontend
    env: node
    region: oregon
    plan: starter
    buildCommand: cd frontend_next && npm install && npm run build
    startCommand: cd frontend_next && npm start
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://callflowai-backend.onrender.com/api/v1
      - key: NEXT_PUBLIC_STRIPE_PUBLIC_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        value: https://callflowai-frontend.onrender.com
      - key: NODE_ENV
        value: production

databases:
  # Optional: PostgreSQL (if not using MongoDB Atlas)
  # - name: callflowai-db
  #   databaseName: callflowai
  #   user: callflowai
  #   plan: starter
EOF

echo "✅ render.yaml created"

# Create .env.example for reference
echo ""
echo "📝 Creating .env.example for reference..."

cat > .env.render.example <<'EOF'
# Backend Environment Variables (Set in Render Dashboard)

# Database
MONGO_URI=mongodb+srv://[USER]:[PASSWORD]@[CLUSTER].mongodb.net/callflowai?retryWrites=true&w=majority

# Security (Auto-generated by Render)
SECRET_KEY=<auto-generated>
JWT_SECRET_KEY=<auto-generated>

# Stripe
STRIPE_SECRET_KEY=sk_live_...
STRIPE_PUBLIC_KEY=pk_live_...

# Twilio
TWILIO_ACCOUNT_SID=AC...
TWILIO_AUTH_TOKEN=...
TWILIO_PHONE_NUMBER=+1...

# WhatsApp
WHATSAPP_TOKEN=...
WHATSAPP_PHONE_NUMBER_ID=...
WHATSAPP_VERIFY_TOKEN=...

# Resend
RESEND_API_KEY=re_...

# n8n
N8N_API_URL=https://n8n.callflowai.com/api/v1
N8N_API_KEY=...

# Frontend
FRONTEND_URL=https://callflowai-frontend.onrender.com
EOF

echo "✅ .env.render.example created"

# Create deployment guide
echo ""
echo "📚 Creating deployment guide..."

cat > RENDER_DEPLOY.md <<'EOF'
# Deploy CallFlow AI to Render

## Prerequisites

1. Render account (sign up at https://render.com)
2. GitHub repository with your code
3. MongoDB Atlas account (or use Render PostgreSQL)

## Deployment Steps

### 1. Connect GitHub Repository

1. Go to https://dashboard.render.com
2. Click "New +" → "Blueprint"
3. Connect your GitHub account
4. Select the `callflowai` repository
5. Render will detect `render.yaml` automatically

### 2. Set Environment Variables

In the Render dashboard, set these secret environment variables:

**Backend Service**:
- `MONGO_URI`: Your MongoDB connection string
- `STRIPE_SECRET_KEY`: Your Stripe secret key
- `TWILIO_ACCOUNT_SID`: Your Twilio account SID
- `TWILIO_AUTH_TOKEN`: Your Twilio auth token
- `RESEND_API_KEY`: Your Resend API key
- `N8N_API_KEY`: Your n8n API key

**Frontend Service**:
- `NEXT_PUBLIC_STRIPE_PUBLIC_KEY`: Your Stripe public key

### 3. Deploy

1. Click "Apply" to deploy both services
2. Wait for build to complete (~5-10 minutes)
3. Services will be available at:
   - Backend: `https://callflowai-backend.onrender.com`
   - Frontend: `https://callflowai-frontend.onrender.com`

### 4. Configure Custom Domain

1. Go to Settings → Custom Domain
2. Add your domain (e.g., `app.callflowai.com`)
3. Update DNS records as instructed
4. Wait for SSL certificate provisioning

### 5. Update CORS Settings

Update `backend/main.py` with your production domain:

```python
app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://app.callflowai.com"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
```

### 6. Test Deployment

1. Visit your frontend URL
2. Sign up for a new account
3. Test payment flow
4. Make a test call
5. Verify automations work

## Monitoring

- **Logs**: View in Render dashboard
- **Metrics**: CPU, memory, requests
- **Alerts**: Set up in Render dashboard

## Scaling

To handle more traffic:

1. Upgrade plan (Starter → Standard → Pro)
2. Add more instances (horizontal scaling)
3. Enable auto-scaling

## Troubleshooting

### Build Fails

- Check build logs in Render dashboard
- Verify `requirements.txt` and `package.json` are correct
- Ensure all dependencies are listed

### Service Won't Start

- Check environment variables are set
- Verify MongoDB connection string
- Check start command in `render.yaml`

### 502 Bad Gateway

- Service is starting (wait 1-2 minutes)
- Check health check endpoint
- Verify port binding (`$PORT`)

## Support

- Render Docs: https://render.com/docs
- Render Community: https://community.render.com
- CallFlow AI Support: support@callflowai.com
EOF

echo "✅ RENDER_DEPLOY.md created"

# Commit files
echo ""
echo "📦 Committing deployment files..."
git add render.yaml .env.render.example RENDER_DEPLOY.md
git commit -m "Add Render deployment configuration"

echo ""
echo "=========================================="
echo "✅ Render deployment files created!"
echo ""
echo "Next steps:"
echo "1. Push to GitHub: git push origin main"
echo "2. Go to https://dashboard.render.com"
echo "3. Click 'New +' → 'Blueprint'"
echo "4. Select your repository"
echo "5. Set environment variables"
echo "6. Click 'Apply' to deploy"
echo ""
echo "📚 See RENDER_DEPLOY.md for detailed instructions"
echo "=========================================="
